#!/bin/sh

current_song=$(mpc current)
if [[ $current_song != "" ]]; then
    pause="" # Other nice-looking symbols: ( )
    play="" # Other nice-looking symbols: ()
    if [[ $(mpc) == *"playing"* ]]; then
        echo "$pause $current_song"
    else 
        echo "$play $current_song"
    fi
fi

