#!/bin/sh

if [ $(cat /sys/class/power_supply/BAT0/status) == "Discharging" ]; then
    battery_lvl=$(cat /sys/class/power_supply/BAT0/capacity)
    if [ $battery_lvl -gt 85 ]; then
        echo " $battery_lvl%"
    elif [ $battery_lvl -gt 60 ]; then
        echo " $battery_lvl%"
    elif [ $battery_lvl -gt 35 ]; then
        echo " $battery_lvl%"
    elif [ $battery_lvl -gt 10 ]; then
        echo " $battery_lvl%"
    else
        echo " $battery_lvl%"
    fi
else
    battery_lvl=$(cat /sys/class/power_supply/BAT0/capacity)
    charging_symbol="" # Other nice-looking symbols: (, charging)
    if [ $battery_lvl -gt 85 ]; then
        echo " $charging_symbol"
    elif [ $battery_lvl -gt 60 ]; then
        echo " $charging_symbol"
    elif [ $battery_lvl -gt 35 ]; then
        echo " $charging_symbol"
    elif [ $battery_lvl -gt 10 ]; then
        echo " $charging_symbol"
    else
        echo " $charging_symbol"
    fi
fi

