#!/bin/bash

COVER=/tmp/"$(mpc current).jpg"

ffmpeg -i ~/Music/"$(mpc current -f %file%)" "$COVER" -y -loglevel quiet

PROGRESS="$(mpc | sed 1d | sed '$ d' | awk '{gsub(/^[^(]*\(|\)[^)]*$/,"",$0);print $0}')"

#TODO: fix this whitespace mess 
notify-send -i "$COVER" "Now playing ($(mpc volume))" "\n$(mpc current)\n\nprogress: $PROGRESS" 
