#!/bin/bash

get_date() {
	#date "+ %H時 %M分 %S秒   %Y年 %m月 %d日"
	date "+ %H時 %M分   %Y年 %m月 %d日"
}

get_battery() {
	if [ $(cat /sys/class/power_supply/BAT0/status) == "Discharging" ]; then
        battery_lvl=$(cat /sys/class/power_supply/BAT0/capacity)
		if [ $battery_lvl -gt 85 ]; then
			echo " $battery_lvl%"
		elif [ $battery_lvl -gt 60 ]; then
			echo " $battery_lvl%"
		elif [ $battery_lvl -gt 35 ]; then
			echo " $battery_lvl%"
		elif [ $battery_lvl -gt 10 ]; then
			echo " $battery_lvl%"
		else
			echo " $battery_lvl%"
		fi
    else
        battery_lvl=$(cat /sys/class/power_supply/BAT0/capacity)
        charging_symbol="" # Other nice-looking symbols: (, charging)
		if [ $battery_lvl -gt 85 ]; then
            echo " $charging_symbol"
		elif [ $battery_lvl -gt 60 ]; then
			echo " $charging_symbol"
		elif [ $battery_lvl -gt 35 ]; then
			echo " $charging_symbol"
		elif [ $battery_lvl -gt 10 ]; then
			echo " $charging_symbol"
		else
			echo " $charging_symbol"
		fi
	fi
}

get_wifi() {
	if [[ $(nmcli d status | grep " connected ") == "" ]]; then
		echo "not connected  "
	else
		echo " $(nmcli -t -f NAME c show --active)  "
	fi
}

get_volume() {
	#bar=("-" "-" "-" "-" "-" "|" "-" "-" "-" "-" "-")

	volume=$(pamixer --get-volume-human)
	if [[ "${volume//\%}" -eq 0 ]]; then
        echo " $volume"
	elif [[ "${volume//\%}" -lt 50 ]]; then
        echo " $volume"
	else
        echo " $volume"
	fi
}

get_current_song() {
    current_song=$(mpc current)
    if [[ $current_song != "" ]]; then
        pause="" # Other nice-looking symbols: ( )
        play="" # Other nice-looking symbols: ()
        if [[ $(mpc) == *"playing"* ]]; then
            echo "$pause $current_song  "
        else 
            echo "$play $current_song  "
        fi
    fi
}

get_xkb_layout() {
	echo " $(xkb-switch)"
}

while true; do
    xsetroot -name "  $(get_xkb_layout)  $(get_current_song)$(get_volume)  $(get_wifi)$(get_battery)  $(get_date) "
	sleep 0.25	# In seconds.
done

